server:
  port: 7000
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8' # 忽略虚拟网卡
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用服务名路由
          lower-case-service-id: true # 请求服务名配置转为小写
          #enabled: false
      # 手动配置路由
      #routes: # 路由数组[路由 就是指定当前请求满足什么条件的时候请求到哪个微服务]
        #- id: product_route # 当前路由的标识
        #  uri: lb://product # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略。也可以请求要转发到的地址
        #  order: 1 # 路由的优先级
        #  predicates: # 断言
        #    - Path=/product/product/** # 当前请求路径满足Path指定的规则时，才进行路由转发
        #  filters: # 过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
        #    - StripPrefix=1 # 转发之前去掉1层路径,去除/gateway
        #    - Log=true,false
        #- id: user_route # 当前路由的标识
        #  uri: lb://user # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略。也可以请求要转发到的地址
        #  order: 2 # 路由的优先级
        #  predicates: # 断言
        #    - Path=/user/user/** # 当前请求路径满足Path指定的规则时，才进行路由转发
        #  filters: # 过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
        #    - StripPrefix=1 # 转发之前去掉1层路径,去除/gateway
        #    - Log=true,false
        #- id: order_route # 当前路由的标识
        #  uri: lb://order # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略。也可以请求要转发到的地址
        #  order: 3 # 路由的优先级
        #  predicates: # 断言
        #    - Path=/order/order/** # 当前请求路径满足Path指定的规则时，才进行路由转发
        #  filters: # 过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改
        #    - StripPrefix=1 # 转发之前去掉1层路径,去除/gateway
        #    - Log=true,false
