server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sca?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&noAccessToProcedureBodies=true&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 3000
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8' # 忽略虚拟网卡
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858 # 指定控制台服务的地址
        # port: 8719 # 跟控制台交流的端口，随意指定一个未使用的端口即可
        # clientIp: 192.168.253.1 # 默认本机Ip
# 开启feign整合sentinel
feign:
  sentinel:
    enabled: true
# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.newbeedaly.alibaba.*.po
# file
file:
  enabled: true
  path: /dev/file

