server:
  port: 8003
spring:
  application:
    name: order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # 配置中心地址
  # SpringCloud 2021版本之后，需要用以下方式导入nacos的配置文件
  config:
    import: nacos:order-dev.yaml
